### ISSUE TITLE
Consider to change variable value

### ISSUE THREAD

**Issue by mangkoran** [psakurai/web-sch-proj-SCAS#9]
https://github.com/psakurai/web-sch-proj-SCAS/blob/e432e79f44f5a9536837565f4fc404cde68d955f/Function/Global/login.php#L25
I don't really know why `ID` is set to user password? I think it will make it less secure. I suggest to change it into user id or just delete it.

**Comment by psakurai** [comment]
declared closed

**Comment by mangkoran** [comment]
Fixed https://github.com/psakurai/web-sch-proj-SCAS/commit/1ec312a08399907705f02542c8eea0235a3b3621
